/*
 * GET /api/file?token=…&k=cover|pdf — the only way generated bytes leave here.
 *
 * There is no public bucket. A panel is a drawing made from a named minor's
 * story and the PDF is something somebody paid for, so both are served through
 * this handler, which checks the token and — for the PDF — checks that the
 * order was actually paid. A storage URL is a permission you cannot revoke.
 *
 * The token is the whole authorisation, which is a deliberate trade: no
 * account, no password, no personal data we did not need. It is 16 random
 * bytes, it only ever travels in a link we email to the buyer, and it is worth
 * exactly one comic. Losing it is the same as forwarding the email.
 */

const { store } = require("../lib/store.js");
const { blobs, keys } = require("../lib/blobs.js");
const { send, requireMethod } = require("../lib/http.js");

/** A filename the buyer will recognise in their downloads folder. */
function filenameFor(job) {
  const story = job.data && job.data.story;
  const bits = [story && story.title, story && story.hero && story.hero.name].filter(Boolean).join(" - ");
  const slug = (bits || "comic")
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, "-").slice(0, 60);
  return `${slug || "comic"}.pdf`;
}

module.exports = async function handler(req, res) {
  if (!requireMethod(req, res, "GET", "HEAD")) return;

  const url = new URL(req.url, "http://localhost");
  const token = (url.searchParams.get("token") || "").replace(/[^\w-]/g, "");
  const kind = url.searchParams.get("k") === "pdf" ? "pdf" : "cover";
  if (!token) return send(res, 400, { error: "falta el token" });

  const job = await store.get(token);
  if (!job) return send(res, 404, { error: "no existe" });

  if (kind === "pdf" && !job.paid_at) {
    return send(res, 402, { error: "este cómic todavía no está pagado" });
  }

  const key = kind === "pdf" ? keys.pdf(token) : keys.cover(token);
  const body = await blobs.get(key);
  if (!body) {
    return send(res, 404, { error: kind === "pdf" ? "el cómic todavía se está dibujando" : "no está" });
  }

  res.statusCode = 200;
  res.setHeader("Content-Type", kind === "pdf" ? "application/pdf" : "image/jpeg");
  res.setHeader("Content-Length", String(body.length));
  // Private and unguessable, so the browser may cache it, but no shared cache
  // and no CDN copy: the token is the permission and it must stay revocable.
  res.setHeader("Cache-Control", "private, max-age=3600");
  if (kind === "pdf") {
    res.setHeader("Content-Disposition", `attachment; filename="${filenameFor(job)}"`);
  }
  if (req.method === "HEAD") return res.end();
  res.end(body);
};
