/*
 * Where the generated bytes live: 78 panels and a PDF per order.
 *
 * Same shape and same reasoning as lib/store.js — one interface, two backends,
 * chosen by an env var so nothing above this file knows which is running:
 *
 *   files     - a directory. Development, and the reason the whole paid flow
 *               can be exercised today without touching shared infrastructure.
 *   supabase  - a private Storage bucket. The real one, and NOT wired to a
 *               live project yet for the same reason store.js is not: that
 *               project is shared with the RPG and cuentos.
 *
 * Why this is not the job record: a comic is about 12 MB of JPEG. Base64 in a
 * row would be 16 MB of JSON read and rewritten on every state transition.
 *
 * Nothing here is public. A panel is a drawing of a named minor's story and the
 * PDF is something somebody paid for; both are served through a handler that
 * checks the token, never by a bucket URL that leaks by being guessed.
 */

const fs = require("fs");
const path = require("path");

const BACKEND = process.env.BLOBS || process.env.STORE || "files";
const DIR = process.env.BLOB_DIR || path.join(__dirname, "..", "out", "blobs");
const BUCKET = process.env.SUPABASE_BUCKET || "comic";

/** Tokens and panel ids only. Anything else is a path traversal waiting to be found. */
function safe(key) {
  const clean = String(key).replace(/[^\w./-]/g, "");
  if (clean.includes("..")) throw new Error("bad blob key");
  return clean;
}

// --- files -------------------------------------------------------------------

const files = {
  async put(key, buffer) {
    const f = path.join(DIR, safe(key));
    fs.mkdirSync(path.dirname(f), { recursive: true });
    fs.writeFileSync(f, buffer);
    return key;
  },

  async get(key) {
    const f = path.join(DIR, safe(key));
    return fs.existsSync(f) ? fs.readFileSync(f) : null;
  },

  async has(key) {
    return fs.existsSync(path.join(DIR, safe(key)));
  },

  /** Everything belonging to one order: panels, sheets, cover, PDF. */
  async removeAll(token) {
    const dir = path.join(DIR, safe(String(token)));
    if (!fs.existsSync(dir)) return 0;
    const n = fs.readdirSync(dir).length;
    fs.rmSync(dir, { recursive: true, force: true });
    return n;
  },

  /** Which of these keys already exist. One call, because 78 round trips is a minute. */
  async which(keys) {
    const out = new Set();
    for (const k of keys) if (await files.has(k)) out.add(k);
    return out;
  },
};

// --- supabase ----------------------------------------------------------------

function supabase() {
  const { createClient } = require("@supabase/supabase-js");
  const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
  const bucket = () => db.storage.from(BUCKET);

  return {
    async put(key, buffer) {
      const { error } = await bucket().upload(safe(key), buffer, {
        contentType: key.endsWith(".pdf") ? "application/pdf" : "image/jpeg",
        upsert: true,
      });
      if (error) throw new Error(error.message);
      return key;
    },

    async get(key) {
      const { data, error } = await bucket().download(safe(key));
      if (error) return null;
      return Buffer.from(await data.arrayBuffer());
    },

    async has(key) {
      const has = await supa.which([key]);
      return has.has(key);
    },

    async removeAll(token) {
      const dir = safe(String(token));
      const { data } = await bucket().list(dir, { limit: 1000 });
      const paths = (data || []).map((f) => `${dir}/${f.name}`);
      if (!paths.length) return 0;
      const { error } = await bucket().remove(paths);
      if (error) throw new Error(error.message);
      return paths.length;
    },

    /*
     * One listing per folder instead of one HEAD per panel: at 78 panels and a
     * round trip each, "what is already drawn?" was costing more than drawing.
     */
    async which(keys) {
      const out = new Set();
      const byDir = new Map();
      for (const k of keys) {
        const dir = path.posix.dirname(safe(k));
        if (!byDir.has(dir)) byDir.set(dir, []);
        byDir.get(dir).push(path.posix.basename(safe(k)));
      }
      for (const [dir, names] of byDir) {
        const { data } = await bucket().list(dir, { limit: 1000 });
        const there = new Set((data || []).map((f) => f.name));
        for (const n of names) if (there.has(n)) out.add(`${dir}/${n}`);
      }
      return out;
    },
  };
}

const supa = BACKEND === "supabase" ? supabase() : null;
const blobs = supa || files;

/** The key layout, in one place so nothing builds these strings by hand. */
const keys = {
  sheet: (token, who) => `${token}/sheet-${who}.jpg`,
  cover: (token) => `${token}/cover.jpg`,
  panel: (token, page, panel) => `${token}/p${page + 1}-${panel + 1}.jpg`,
  pdf: (token) => `${token}/comic.pdf`,
};

module.exports = { blobs, keys, BACKEND, BUCKET };
