/*
 * Writes assets/js/options.js from lib/collection.js so the order form and
 * the viewer use exactly the ids the server validates. Run after editing the
 * collection; the output is committed.
 *
 * Usage: node scripts/build-options.js
 */

const fs = require("fs");
const path = require("path");
const C = require("../lib/collection.js");

const pick = (list) => list.map(({ id, es, en }) => ({ id, es, en }));
const options = {
  genders: pick(C.GENDERS),
  ageBands: pick(C.AGE_BANDS),
  hairColors: pick(C.HAIR_COLORS),
  hairTypes: pick(C.HAIR_TYPES),
  skinTones: pick(C.SKIN_TONES),
  pets: pick(C.PETS),
  hobbies: pick(C.HOBBIES),
  themes: pick(C.THEMES),
  moments: pick(C.MOMENTS),
  tones: pick(C.TONES),
  // relations carry `adult` so the form can stop offering a child's age
  // band to a father — the option list and the validator must agree.
  relations: C.RELATIONS.map(({ id, es, en, adult }) => ({ id, es, en, adult })),
  personAges: pick(C.PERSON_AGES),
  maxPeople: C.MAX_PEOPLE,
};

const out = path.join(__dirname, "..", "assets", "js", "options.js");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `// Generated by scripts/build-options.js — do not edit by hand.\nwindow.CUENTOS_OPTIONS = ${JSON.stringify(options, null, 2)};\n`);
console.log(`[cuentos] wrote ${out}`);
