/*
 * Generates the form's option lists from lib/catalog.js.
 *
 * The form is never edited by hand — same rule as cuentos/scripts/build-options.js.
 * If a value is not in the catalogue the pipeline has not been designed for it,
 * and a hand-edited <option> is exactly how a value the validator rejects ends
 * up in front of a paying customer.
 *
 * Usage: node scripts/build-options.js
 * Output: assets/js/options.js  (committed)
 */

const fs = require("fs");
const path = require("path");
const C = require("../lib/catalog.js");

/* id -> the label the buyer reads, in both languages. The English fragment the
   illustrator uses never leaves lib/catalog.js. */
const keyed = (group, obj) =>
  Object.keys(obj).map((id) => ({ id, label: C.label(group, id), en: C.label(group, id, "en") }));

const data = {
  styles: Object.entries(C.STYLES).map(([id, s]) => ({ id, label: s.label, hint: s.hint })),
  tropes: Object.entries(C.TROPES).map(([id, t]) => ({ id, label: t.label })),
  tones: Object.entries(C.TONES).map(([id, t]) => ({ id, label: t.label, hint: t.hint })),
  traits: Object.entries(C.TRAITS).map(([id, t]) => ({ id, label: t.label })),
  ageBands: Object.entries(C.AGE_BANDS).map(([id, b]) => ({ id, label: b.label, pages: b.pages })),
  // Appearance lists keep their Spanish keys as labels: they are short enough
  // that the key IS the label, and a second translation table would drift.
  hairShape: keyed("hairShape", C.HAIR_SHAPE),
  hairColour: keyed("hairColour", C.HAIR_COLOUR),
  eyes: keyed("eyes", C.EYES),
  skin: keyed("skin", C.SKIN),
  build: keyed("build", C.BUILD),
  marks: keyed("marks", C.MARKS),
  relations: Object.entries(C.RELATIONS).map(([id, label]) => ({ id, label })),
};

const dest = path.join(__dirname, "..", "assets", "js", "options.js");
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(
  dest,
  "/* GENERATED by scripts/build-options.js from lib/catalog.js — do not edit. */\n" +
    `window.COMIC_OPTIONS = ${JSON.stringify(data, null, 2)};\n`
);

const counts = Object.entries(data).map(([k, v]) => `${k}:${v.length}`).join(" ");
console.log(`assets/js/options.js escrito — ${counts}`);
